### PR TITLE
[BUG] Fix user list visual bug and user page wrong grade showing.

### LINKED ISSUE #45: [BUG] Students list not showed correctly
**Describe the bug**
It shows the last column as 0s when a student is logged in.

**To Reproduce**

1. Login as a student
2. Click on Grades, then Students
3. See the table

**Expected behavior**
The Table should be shown without the last column
 
**Screenshots**
Screenshot 2021-01-19 185014

**Desktop (please complete the following information):**

* OS: Windows
* Version 10

**Additional context**
-

### LINKED ISSUE #46: [BUG] Fix grades on user page.
**Describe the bug**
Grades should be anonymous. Currently, you can see the grades awarded by any user to any team. Only on the logged in user's profile should they see the grades they awarded. Grades from teams should be displayed on the user page.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by filipdutescu**
Fixes #45, fixes #46 

## Implemented fixes

* fix displaying grades awarded instead of received in the user page
* fix user list bug showing a '0'

### CODE REVIEW

File: client/src/components/UsersTable.js [hunk 1]
```diff
@@ -53,8 +72,7 @@ export default function UsersTable({ useAuthHandler, onlyStudents, onlyProfessor
                                         <th><Link to={`/user/${j.username}`}>{j.username}</Link></th>
                                         <th>{j.surname}</th>
                                         <th>{j.name}</th>
-                                        { !onlyProfessors && currentUser && currentUser.is_professor &&
-                                        <th><Button size="xs" color="danger" onClick={async () => await deleteUser(j.id)}>Remove</Button></th> }
+                                        { renderRemoveButton() }
```
Comment (b0tw) [inline client/src/components/UsersTable.js]: You need to call the function with the student id in order to make the deletion work
```suggestion
                                        { renderRemoveButton(j.id) }
```

**Review by b0tw — CHANGES_REQUESTED** [review]

File: client/src/components/UsersTable.js (hunk 1 above)
Comment (filipdutescu) [reply client/src/components/UsersTable.js]: good catch 👍

**Review by b0tw — APPROVED** [review]
Good
